### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by gerdesj** [arsham/figurine#1]
I'm not too familiar with go.  I managed to run the go get command which is a little sparse for readable output.  I then run the example $ figurine command which fails because I do not have my PATH setup for binaries created by go get.

After a little poking around my filesystem, this might be a better example:
`$ ~/go/bin/figurine text`

Those people who are familiar with go will probably automatically translate the paths and those like me who happen to have go installed by something else who wanted to have a play with this will also be well served.

**Comment by arsham** [comment]
You could get the binary from [here](https://github.com/arsham/figurine/releases) too, without needing to install go. I will update the readme file.
