### ISSUE TITLE
Error when using as a library with gomod

### ISSUE THREAD

**Issue by retr0h** [arsham/figurine#7]
I have a utility I am writing.  I am using go 1.11.1 and the project uses go modules.  When importing figurine and running the following code:

```
if err := figurine.Write(os.Stdout, input, fontName); err != nil {
    log.Fatal(err)
}
```

I receive the following with `go test`

```
go: extracting github.com/arsham/figurine v0.3.0
-> unzip /Users/jodewey/go/pkg/mod/cache/download/github.com/arsham/figurine/@v/v0.3.0.zip: malformed file path "bin/Patorjk's Cheese.flf": invalid char '\''
```

**Comment by arsham** [comment]
Hi, sorry for the late response.

Can you give it another go please?
