### ISSUE TITLE
Unresolved library dependencies

### ISSUE THREAD

**Issue by Nuru** [arsham/figurine#8]
Versions 1.1.1 and 1.1.2 of `figurine` do not run on stock Debian or RedHat [UBI](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) (formerly Centos). 

```
figurine: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by figurine)
figurine: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by figurine)
```

This is usually a consequence of compiling with `CGO_ENABLED=1` and can be fixed by setting `CGO_ENABLED=0`.

**Comment by arsham** [comment]
Thank you for reporting. I will make a new release.

**Comment by arsham** [comment]
@Nuru I have made a new [release](https://github.com/arsham/figurine/releases/tag/v1.1.3).

**Comment by Nuru** [comment]
Thank you.
